import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar/navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function PagesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main>
      <Navbar></Navbar>
      {children}
    </main>
  );
}
